# my global config
global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets: [ "host.docker.internal:9091" ]
  - job_name: "chat"
    static_configs:
      - targets: [ "host.docker.internal:9095" ]